### ISSUE TITLE
  请问新手如何调试与执行源码? makefile 执行是成功的. 在clion 上运行报的错如下.

### ISSUE THREAD

**Issue by ZhuoSiChen** [UncP/aili#1]
====================[ Build | aili | Debug ]====================================
/home/muxin/devTool/clion-2019.2.5/bin/cmake/linux/bin/cmake --build /home/muxin/IdeaProjects/aili/cmake-build-debug --target aili -- -j 4
Scanning dependencies of target aili
[  3%] Building C object CMakeFiles/aili.dir/palm/metric.c.o
[  6%] Building C object CMakeFiles/aili.dir/test/art_test.c.o
[  9%] Building C object CMakeFiles/aili.dir/test/mass_node_test.c.o
[ 12%] Building C object CMakeFiles/aili.dir/test/mass_tree_test.c.o
/home/muxin/IdeaProjects/aili/palm/metric.c:12:10: fatal error: c_hashmap/hashmap.h: No such file or directory
 #include <c_hashmap/hashmap.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/aili.dir/build.make:257: recipe for target 'CMakeFiles/aili.dir/palm/metric.c.o' failed
make[3]: *** [CMakeFiles/aili.dir/palm/metric.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/muxin/IdeaProjects/aili/test/mass_node_test.c:14:10: fatal error: ../mass/node.h: No such file or directory
 #include "../mass/node.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
/home/muxin/IdeaProjects/aili/test/art_test.c: In function ‘test_adaptive_radix_tree_structure’:
/home/muxin/IdeaProjects/aili/test/art_test.c:171:3: error: too many arguments to function ‘adaptive_radix_tree_put’
   adaptive_radix_tree_put(art, key1, 5, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/muxin/IdeaProjects/aili/test/art_test.c:18:0:
/home/muxin/IdeaProjects/aili/test/../art/art.h:16:5: note: declared here
 int adaptive_radix_tree_put(adaptive_radix_tree *art, const void *key, size_t len);
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/muxin/IdeaProjects/aili/test/art_test.c:172:3: error: too many arguments to function ‘adaptive_radix_tree_put’
   adaptive_radix_tree_put(art, key2, 6, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/muxin/IdeaProjects/aili/test/art_test.c:18:0:
/home/muxin/IdeaProjects/aili/test/../art/art.h:16:5: note: declared here
 int adaptive_radix_tree_put(adaptive_radix_tree *art, const void *key, size_t len);
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/muxin/IdeaProjects/aili/test/art_test.c:173:3: error: too many arguments to function ‘adaptive_radix_tree_put’
   adaptive_radix_tree_put(art, key3, 7, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/muxin/IdeaProjects/aili/test/art_test.c:18:0:
/home/muxin/IdeaProjects/aili/test/../art/art.h:16:5: note: declared here
 int adaptive_radix_tree_put(adaptive_radix_tree *art, const void *key, size_t len);
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/muxin/IdeaProjects/aili/test/art_test.c:197:3: error: too many arguments to function ‘adaptive_radix_tree_put’
   adaptive_radix_tree_put(art, key1, 7, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/muxin/IdeaProjects/aili/test/art_test.c:18:0:
/home/muxin/IdeaProjects/aili/test/../art/art.h:16:5: note: declared here
 int adaptive_radix_tree_put(adaptive_radix_tree *art, const void *key, size_t len);
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/muxin/IdeaProjects/aili/test/art_test.c:198:3: error: too many arguments to function ‘adaptive_radix_tree_put’
   adaptive_radix_tree_put(art, key2, 6, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/muxin/IdeaProjects/aili/test/art_test.c:18:0:
/home/muxin/IdeaProjects/aili/test/../art/art.h:16:5: note: declared here
 int adaptive_radix_tree_put(adaptive_radix_tree *art, const void *key, size_t len);
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/muxin/IdeaProjects/aili/test/art_test.c:199:3: error: too many arguments to function ‘adaptive_radix_tree_put’
   adaptive_radix_tree_put(art, key3, 5, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/muxin/IdeaProjects/aili/test/art_test.c:18:0:
/home/muxin/IdeaProjects/aili/test/../art/art.h:16:5: note: declared here
 int adaptive_radix_tree_put(adaptive_radix_tree *art, const void *key, size_t len);
     ^~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/aili.dir/build.make:335: recipe for target 'CMakeFiles/aili.dir/test/mass_node_test.c.o' failed
make[3]: *** [CMakeFiles/aili.dir/test/mass_node_test.c.o] Error 1
CMakeFiles/aili.dir/build.make:309: recipe for target 'CMakeFiles/aili.dir/test/art_test.c.o' failed
make[3]: *** [CMakeFiles/aili.dir/test/art_test.c.o] Error 1
/home/muxin/IdeaProjects/aili/test/mass_tree_test.c: In function ‘test_mass_tree’:
/home/muxin/IdeaProjects/aili/test/mass_tree_test.c:135:3: warning: implicit declaration of function ‘mass_tree_validate’; did you mean ‘mass_tree_get’? [-Wimplicit-function-declaration]
   mass_tree_validate(mt);
   ^~~~~~~~~~~~~~~~~~
   mass_tree_get
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/aili.dir/all' failed
make[2]: *** [CMakeFiles/aili.dir/all] Error 2
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/aili.dir/rule' failed
make[1]: *** [CMakeFiles/aili.dir/rule] Error 2
Makefile:118: recipe for target 'aili' failed
make: *** [aili] Error 2

**Comment by UncP** [comment]
我没写 cmake，你看 README 里的提示

**Comment by ZhuoSiChen** [comment]
能否指导下如何debug 程序
muxin@muxin-G3:~/IdeaProjects/aili/example$ make
cd .. && make lib "DFLAGS+=-DAllocator"
make[1]: Entering directory '/home/muxin/IdeaProjects/aili'
make third_party
make[2]: Entering directory '/home/muxin/IdeaProjects/aili'
cd third_party/c_hashmap && gcc -std=c99 -D_GNU_SOURCE -Wall -Werror -Wextra -O3 -fno-strict-aliasing -c hashmap.c -o hashmap.o && ar rcs libhashmap.a hashmap.o
make[2]: Leaving directory '/home/muxin/IdeaProjects/aili'
ar rcs libaili.a palm/node.o palm/bounded_queue.o palm/worker.o palm/palm_tree.o palm/metric.o palm/allocator.o palm/node.o palm/allocator.o blink/node.o blink/blink_tree.o blink/mapping_array.o mass/mass_node.o mass/mass_tree.o art/art_node.o art/art.o third_party/c_hashmap/hashmap.o
make[1]: Leaving directory '/home/muxin/IdeaProjects/aili'
gcc -std=c99 -o palm_tree palm_tree.c ../libaili.a -lpthread -lm
gcc -std=c99 -o blink_tree blink_tree.c ../libaili.a -lpthread -lm -D_GNU_SOURCE
blink_tree.c: In function ‘main’:
blink_tree.c:26:12: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘void *’ [-Wformat=]
   printf("%s\n", value);
           ~^
           %p
blink_tree.c:33:12: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘void *’ [-Wformat=]
   printf("%s\n", value);
           ~^
           %p
gcc -std=c99 -o mass_tree mass_tree.c ../libaili.a -lpthread -lm
gcc -std=c99 -o adaptive_radix_tree adaptive_radix_tree.c ../libaili.a -lpthread -lm
muxin@muxin-G3:~/IdeaProjects/aili/example$ gdb ./palm_tree 
GNU gdb (Ubuntu 8.1-0ubuntu3.1) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./palm_tree...(no debugging symbols found)...done.
(gdb) list
No symbol table is loaded.  Use the "file" command.
(gdb) file palm_tree
Reading symbols from palm_tree...(no debugging symbols found)...done.

**Comment by ZhuoSiChen** [comment]
成功了.
在 gcc 后面加 -g 选项
```makefile	gcc -std=c99 -o palm_tree palm_tree.c ../libaili.a -lpthread -lm -g
	gcc -std=c99 -o blink_tree blink_tree.c ../libaili.a -lpthread -lm -D_GNU_SOURCE -g
	gcc -std=c99 -o mass_tree mass_tree.c ../libaili.a -lpthread -lm -g
	gcc -std=c99 -o adaptive_radix_tree adaptive_radix_tree.c ../libaili.a -lpthread -lm -g
```
然后再用gdbserver 启动example 里的程序 配置端口
然后再用clion 远程链接到程序中去
