### ISSUE TITLE
palm tree在多线程情况下会出现卡死的情况

### ISSUE THREAD

**Issue by gtygo** [UncP/aili#5]
rt
我把线程数提高到8偶尔会卡死，提高到64一动不动

**Comment by UncP** [comment]
pstack pid 给个堆栈看看？另外你的机器多少核

**Comment by gtygo** [comment]
pstack拿不到堆栈信息，我机器是96核的
![image](https://user-images.githubusercontent.com/24492354/80303763-d7bcf680-87e4-11ea-80ff-3f4e64ea4910.png)

**Comment by gtygo** [comment]
另外刚拉下来的时候代码编译不过，我改了两行：
![image](https://user-images.githubusercontent.com/24492354/80303832-49954000-87e5-11ea-8f2e-23334612badd.png)

**Comment by UncP** [comment]
想起来了，palm tree 使用的队列里有 bug，一直没修，所以可能会在结束之前卡住，如果卡住的时候 cpu 使用几乎为0，那应该就是这个问题了，你看下 bounded_queue。

**Comment by gtygo** [comment]
了解，正在研究art tree，性能是真滴强

**Comment by skyelves** [comment]
请问下palm tree里的bug修复后的版本有吗

**Comment by UncP** [comment]
没有修，你自己修吧，在 bounded_queue 里面，没几行代码的

**Comment by skyelves** [comment]
我去看看
