### ISSUE TITLE
art插入的疑问

### ISSUE THREAD

**Issue by skyelves** [UncP/aili#7]
https://github.com/UncP/aili/blob/a2f3225ed0ba7ec6f14ae8ade761525d64f60659/test/one_test.c#L124-L127
这里插入为什么要malloc16个byte，同时空出第一个byte，是有什么concern吗

**Comment by UncP** [comment]
第一个 byte 用来存放 key 长度，第125行。

**Comment by skyelves** [comment]
为什么需要把长度写两次，一个key[0]，另一个adaptive_radix_tree_put的第三个参数？而且传入adaptive_radix_tree_put这个函数中时并没有用到key[0]，但是函数里面却会用到key[0]这个值，有点不太理解这样做的目的

**Comment by UncP** [comment]
节省每个节点的大小，这样就不用在节点里添加 len[N] 这样的字段了
