### ISSUE TITLE
Delete operation on Multi ART

### ISSUE THREAD

**Issue by paulocoghi** [UncP/aili#9]
Hi! First of all, congratulations for the performance achieved on your implementation!

I would like to know if you plan to implement the delete operation on your Multi ART algorithm.

**Comment by UncP** [comment]
i did not implement it.

Paulo Coghi ***@***.***>于2021年11月3日 周三下午7:57写道：

**Comment by paulocoghi** [comment]
I understand. Thanks for the fast response!
